# Generated by Django 5.2.1 on 2025-05-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nivel', 'descripcion'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AddField(
            model_name='cargo',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nivel jerárquico del cargo (1-10)'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='responsabilidades',
            field=models.TextField(blank=True, help_text='Responsabilidades y funciones del cargo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salario base recomendado', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=models.CharField(help_text='Nombre o descripción del cargo', max_length=100, unique=True),
        ),
    ]
