# Generated by Django 5.2.1 on 2025-05-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cargo_options_cargo_nivel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['descripcion'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AddField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descripción'),
        ),
    ]
