# Generated by Django 5.2.1 on 2025-05-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_departamento_options_departamento_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocontrato',
            options={'verbose_name': 'Tipo de Contrato', 'verbose_name_plural': 'Tipos de Contrato'},
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='nombre',
            field=models.CharField(default='Contrato estándar', max_length=50, verbose_name='Nombre del contrato'),
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción del contrato'),
        ),
    ]
